name: task0

on:
  push:

  schedule:
    - cron: "0 6 * * *"

jobs:
  clone:

    runs-on: ubuntu-latest

    steps:
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'alejandrodgz'
          repository: 'holbertonschool-validation'
      - name: Access cloned repository content
        run: |
          cd holbertonschool-validation/tree/master/module3_task0
          make help