name: module3_task0
on:
  push:

  schedule:
    - cron: "0 6 * * *"

jobs:
  build:

    runs-on: ubuntu-lastest

    steps:
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'alejandrodgz'
          repository: 'holbertonschool-validation'
      - name: update first
        run: apt update
      - name: install make
        run: apt-get update && apt-get install -y make
      - name: install curl
        run: apt install -y curl
      - name: install hugo
        run: curl -L https://github.com/gohugoio/hugo/releases/download/v0.109.0/hugo_extended_0.109.0_linux-amd64.deb -o hugo.deb
      - name: last step
        run: apt install ./hugo.deb
      - name: build the website
        working-directory: ./holbertonschool-validation/module3_task0
        run: make build
