name: module3_task1
on:
  push:

  schedule:
    - cron: "0 6 * * *"

jobs:
  clone:

    runs-on: ubuntu-18.04

    steps:
      - name: Clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'alejandrodgz'
          repository: 'holbertonschool-validation'
      - name: run update and isntall make
        run: apt-get update && apt-get install -y make
      - name: run update curl
        run: apt-get update && apt-get install -y wget
      - name: hugo with wget
        run: wget https://github.com/gohugoio/hugo/releases/download/v0.84.0/hugo_extended_0.84.0_Linux-64bit.deb
      - name: hugo instal
        run: dpkg -i hugo_extended_0.84.0_Linux-64bit.deb
      - name: make command
        working-directory: ./holbertonschool-validation/module3_task1
        run: make build
