name: module3_task1
on:
  push:

  schedule:
    - cron: "0 6 * * *"

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'alejandrodgz'
          repository: 'holbertonschool-validation'
      - name: call script
        run: cd module3_task1 && ./setup.sh
      - name: make command
        run: cd module3_task1 && make build
