name: module3_task0
on:
  push:

  schedule:
    - cron: "0 6 * * *"

jobs:
  clone:

    runs-on: ubuntu-latest

    steps:
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'alejandrodgz'
          repository: 'holbertonschool-validation'
      - name: Build Hugo
        uses: lowply/build-hugo@v0.106.0
      - name: Install Composer Dependencies
        working-directory: ./holbertonschool-validation/module3_task0
        run: make help
