name: module3_task0
on:
  push:

  schedule:
    - cron: "0 6 * * *"

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'alejandrodgz'
          repository: 'holbertonschool-validation'
      - name: Build Hugo
        uses: lowply/build-hugo@v0.106.0
      - name: build the website
        working-directory: ./holbertonschool-validation/module3_task0
        run: make build
