name: module3_task1
on:
  push:

  schedule:
    - cron: "0 6 * * *"

jobs:
  clone:

    runs-on: ubuntu-18.04

    steps:
      - name: Clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'alejandrodgz'
          repository: 'holbertonschool-validation'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
      - name: make command
        working-directory: ./holbertonschool-validation/module3_task1
        run: make build
