name: module3_task1
on:
  push:

  schedule:
    - cron: "0 6 * * *"

jobs:
  clone:

    runs-on: ubuntu-18.04

    steps:
      - name: clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'alejandrodgz'
          repository: 'holbertonschool-validation'
      - name: update make
        run: apt-get update && apt-get install -y make
      - name: Install Composer Dependencies
        working-directory: ./holbertonschool-validation/module3_task0
        run: make help