name: module3_task1
on:
  push:

  schedule:
    - cron: "0 6 * * *"

jobs:
  clone:

    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'alejandrodgz'
          repository: 'holbertonschool-validation'
      - name: Install Composer Dependencies
        working-directory: ./holbertonschool-validation/module3_task1
        run: make help
