name: module3_task2
on:
  push:
  schedule:
    - cron: "0 6 * * *"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'alejandrodgz'
          repository: 'holbertonschool-validation'
      - name: call script
        working-directory: ./holbertonschool-validation/module3_task2
        run: ./setup.sh && make build
      - name: install markdownlint
        run: npm install -g markdownlint-cli
      - name: run make
        working-directory: ./holbertonschool-validation/module3_task2
        run: make package
