name: release-drafter
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    tags:
      - "*.*.*"
  schedule:
    - cron: "0 6 * * *"

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-18.04
    steps:

      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
          config-name: release_drafter.yml
        # disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}with:
          publish: true
          config-name: release_drafter.yml
        # disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
