name: release-drafter
on:
  push:
    branches: [master]
  pull_request:
    tags:
      - "*.*.*"
  schedule:
    - cron: "0 6 * * *"

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-18.04
    steps:
      - name: draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
